name: Sync to GitLab

on:
  push:
    branches: ['**']

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push full history to GitLab
        run: |
          git config --global http.sslVerify false
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_REPO_PATH }}.git
          git push gitlab HEAD:github-sync --force